
export type Monster = {
    index: string,
    name: string,
    size: string,
    type: string,
    subtype: string | null,
    alignment: string,
    armor_class: number,
    hit_points: number,
    speed: object,
    strength: number,
    dexerity: number,
    constitution: number,
    intelligence: number,
    wisdom: number,
    charisma: number,
    proficiencies: object[],
    damage_vulnerabilities: string[],
    damage_resistances: string[],
    damage_immunities: string[],
    condition_immunities: string[],
    senses: object,
    languages: string,
    challenge_rating: number,
    xp: number,
    special_abilities: object[],
    actions: object[],
    legendary_actions: object[],
    url: string,
}